/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFalhasRouteImport } from './routes/_authenticated/falhas'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedFilamentosRouteImport } from './routes/_authenticated/filamentos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMaquinasRouteImport } from './routes/_authenticated/maquinas'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/_authenticated/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/_authenticated/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFalhasRoute = AuthenticatedFalhasRouteImport.update({
  id: '/_authenticated/falhas',
  path: '/falhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/_authenticated/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/_authenticated/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFilamentosRoute = AuthenticatedFilamentosRouteImport.update({
  id: '/_authenticated/filamentos',
  path: '/filamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/_authenticated/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMaquinasRoute = AuthenticatedMaquinasRouteImport.update({
  id: '/_authenticated/maquinas',
  path: '/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/_authenticated/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/_authenticated/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/falhas': typeof AuthenticatedFalhasRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/filamentos': typeof AuthenticatedFilamentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/falhas': typeof AuthenticatedFalhasRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/filamentos': typeof AuthenticatedFilamentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/falhas': typeof AuthenticatedFalhasRoute
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/filamentos': typeof AuthenticatedFilamentosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/maquinas': typeof AuthenticatedMaquinasRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/falhas'
    | '/farm'
    | '/fila'
    | '/filamentos'
    | '/financeiro'
    | '/maquinas'
    | '/orcamento'
    | '/vendas'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catalogo'
    | '/clientes'
    | '/configuracoes'
    | '/falhas'
    | '/farm'
    | '/fila'
    | '/filamentos'
    | '/financeiro'
    | '/maquinas'
    | '/orcamento'
    | '/vendas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/catalogo'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/falhas'
    | '/_authenticated/farm'
    | '/_authenticated/fila'
    | '/_authenticated/filamentos'
    | '/_authenticated/financeiro'
    | '/_authenticated/maquinas'
    | '/_authenticated/orcamento'
    | '/_authenticated/vendas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFalhasRoute: typeof AuthenticatedFalhasRoute
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFilamentosRoute: typeof AuthenticatedFilamentosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMaquinasRoute: typeof AuthenticatedMaquinasRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/falhas': {
      id: '/_authenticated/falhas'
      path: '/falhas'
      fullPath: '/falhas'
      preLoaderRoute: typeof AuthenticatedFalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/filamentos': {
      id: '/_authenticated/filamentos'
      path: '/filamentos'
      fullPath: '/filamentos'
      preLoaderRoute: typeof AuthenticatedFilamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/maquinas': {
      id: '/_authenticated/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AuthenticatedMaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFalhasRoute: AuthenticatedFalhasRoute,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFilamentosRoute: AuthenticatedFilamentosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMaquinasRoute: AuthenticatedMaquinasRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
